services:
  - type: web
    name: cloudix-store
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        value: "5255297864"
      - key: WEBAPP_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.11"
